In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.3.0


In [2]:
class MLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = tf.keras.layers.Flatten()    # Flatten层将除第一维（batch_size）以外的维度展平
        self.dense1 = tf.keras.layers.Dense(units=256, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(units=10)

    def call(self, inputs):
        x = self.flatten(inputs)
        x = self.dense1(x)
        output = self.dense2(x)
        return output


In [3]:
X = tf.random.uniform((2,20))
net = MLP()
net(X)


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.03793843, -0.06732808, -0.27377078, -0.6562847 ,  0.18311906,
        -0.0312659 ,  0.01162998, -0.02933572, -0.08463301, -0.05277662],
       [-0.08121902, -0.2560511 ,  0.05197459, -0.6256269 ,  0.07057261,
         0.10138179,  0.08102965,  0.02419386,  0.03854957, -0.01818217]],
      dtype=float32)>

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation=tf.nn.relu),
    tf.keras.layers.Dense(10),
])

model(X)


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.14476535, -0.15894848,  0.26022843, -0.29866892,  0.4004117 ,
         0.20299459,  0.30343643, -0.21258703, -0.04609922, -0.294633  ],
       [-0.03424529, -0.03831484,  0.2489444 , -0.27127638,  0.34687895,
         0.26372582,  0.15182543, -0.13192058, -0.05904692, -0.3846816 ]],
      dtype=float32)>

In [5]:
class FancyMLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = tf.keras.layers.Flatten()
        self.rand_weight = tf.constant(
            tf.random.uniform((20,20)))
        self.dense = tf.keras.layers.Dense(units=20, activation=tf.nn.relu)

    def call(self, inputs):         
        x = self.flatten(inputs)   
        x = tf.nn.relu(tf.matmul(x, self.rand_weight) + 1)
        x = self.dense(x)    
        while tf.norm(x) > 1:
            x /= 2
        if tf.norm(x) < 0.8:
            x *= 10
        return tf.reduce_sum(x)


In [6]:
net = FancyMLP()
net(X)

<tf.Tensor: shape=(), dtype=float32, numpy=24.663113>

In [7]:
class NestMLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.net = tf.keras.Sequential()
        self.net.add(tf.keras.layers.Flatten())
        self.net.add(tf.keras.layers.Dense(64, activation=tf.nn.relu))
        self.net.add(tf.keras.layers.Dense(32, activation=tf.nn.relu))
        self.dense = tf.keras.layers.Dense(units=16, activation=tf.nn.relu)


    def call(self, inputs):         
        return self.dense(self.net(inputs))

net = tf.keras.Sequential()
net.add(NestMLP())
net.add(tf.keras.layers.Dense(20))
net.add(FancyMLP())

net(X)


<tf.Tensor: shape=(), dtype=float32, numpy=18.210407>